DATA_CONCRETE = [{"angle": 0,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон0-exported.txt",
                  },
                 {"angle": 20,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон20-exported.txt",
                  },
                 {"angle": 30,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон30-exported.txt",
                  },
                 {"angle": 40,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон40-exported.txt",
                  },
                 {"angle": 50,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон50-exported.txt",
                  },
                 {"angle": 55,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон55-exported.txt",
                  },
                 {"angle": 60,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон60-exported.txt",
                  },
                 {"angle": 65,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон65-exported.txt",
                  },
                 {"angle": 70,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон70-exported.txt",
                  },
                 {"angle": 75,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон75-exported - Cloud.txt",
                  },
                 {"angle": 80,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон80-exported - Cloud.txt",
                  },
                 {"angle": 85,
                  "type_": "wet",
                  "material": "concrete",
                  "filepath": "src/wet_concrete/ВлБетон85-exported - Cloud.txt",
                  },

                 #################### DRY CONCRETE ####################

                 {"angle": 0,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон0-exported.txt",
                  },
                 {"angle": 20,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон20-exported.txt",
                  },
                 {"angle": 30,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон30-exported.txt",
                  },
                 {"angle": 40,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон40-exported.txt",
                  },
                 {"angle": 50,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон50-exported.txt",
                  },
                 {"angle": 55,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон55-exported.txt",
                  },
                 {"angle": 60,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон60-exported.txt",
                  },
                 {"angle": 65,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон65-exported.txt",
                  },
                 {"angle": 70,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон70-exported.txt",
                  },
                 {"angle": 75,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон75-exported.txt",
                  },
                 {"angle": 80,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон80-exported.txt",
                  },
                 {"angle": 85,
                  "type_": "dry",
                  "material": "concrete",
                  "filepath": "src/dry_concrete/Бетон85-exported.txt",
                  },
                 ]

DATA_STEEL = [{"angle": 0,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_0-exported.txt",
               },
              {"angle": 20,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_20-exported.txt",
               },
              {"angle": 30,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_30-exported.txt",
               },
              {"angle": 40,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_40-exported.txt",
               },
              {"angle": 50,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_50-exported.txt",
               },
              {"angle": 55,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_55-exported.txt",
               },
              {"angle": 60,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_60-exported.txt",
               },
              {"angle": 65,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_65-exported.txt",
               },
              {"angle": 70,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_70-exported.txt",
               },
              {"angle": 75,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_75-exported.txt",
               },
              {"angle": 80,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_80-exported.txt",
               },
              {"angle": 85,
               "type_": "dry",
               "material": "steel",
               "filepath": "src/dry_steel/dry_steel_85-exported.txt",
               },

              #######################

              {"angle": 0,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_0-exported.txt",
               },
              {"angle": 20,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_20-exported.txt",
               },
              {"angle": 30,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_30-exported.txt",
               },
              {"angle": 40,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_40-exported.txt",
               },
              {"angle": 50,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_50-exported.txt",
               },
              {"angle": 55,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_55-exported.txt",
               },
              {"angle": 60,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_60-exported.txt",
               },
              {"angle": 65,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_65-exported.txt",
               },
              {"angle": 70,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_50-exported.txt",
               },
              {"angle": 75,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_75-exported.txt",
               },
              {"angle": 80,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_80-exported.txt",
               },
              {"angle": 85,
               "type_": "wet",
               "material": "steel",
               "filepath": "src/wet_steel/wet_steel_85-exported.txt",
               },
              ]

DATA_BRICK = [{"angle": 0,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_0-exported.txt",
               },
              {"angle": 20,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_20-exported.txt",
               },
              {"angle": 30,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_30-exported.txt",
               },
              {"angle": 40,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_40-exported.txt",
               },
              {"angle": 50,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_50-exported.txt",
               },
              {"angle": 55,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_55-exported.txt",
               },
              {"angle": 60,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_60-exported.txt",
               },
              {"angle": 65,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_65-exported.txt",
               },
              {"angle": 70,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_70-exported.txt",
               },
              {"angle": 75,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_75-exported.txt",
               },
              {"angle": 80,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_80-exported.txt",
               },
              {"angle": 85,
               "type_": "dry",
               "material": "brick",
               "filepath": "src/dry_brick/dry_kirp_85-exported.txt",
               },

              #######################

              {"angle": 0,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_0-exported.txt",
               },
              {"angle": 20,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_20-exported.txt",
               },
              {"angle": 30,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_30-exported.txt",
               },
              {"angle": 40,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_40-exported.txt",
               },
              {"angle": 50,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_50-exported.txt",
               },
              {"angle": 55,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_55-exported.txt",
               },
              {"angle": 60,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_60-exported.txt",
               },
              {"angle": 65,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_65-exported.txt",
               },
              {"angle": 70,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_70-exported.txt",
               },
              {"angle": 75,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_75-exported.txt",
               },
              {"angle": 80,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_80-exported.txt",
               },
              {"angle": 85,
               "type_": "wet",
               "material": "brick",
               "filepath": "src/wet_brick/wet_kirp_85-exported.txt",
               },
              ]

DATA_PAINTED_STEEL = [{"angle": 0,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_0-exported.txt",
                       },
                      {"angle": 20,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_20-exported.txt",
                       },
                      {"angle": 30,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_30-exported.txt",
                       },
                      {"angle": 40,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_40-exported.txt",
                       },
                      {"angle": 50,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_50-exported.txt",
                       },
                      {"angle": 55,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_55-exported.txt",
                       },
                      {"angle": 60,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_60-exported.txt",
                       },
                      {"angle": 65,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_65-exported.txt",
                       },
                      {"angle": 70,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_70-exported.txt",
                       },
                      {"angle": 75,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_75-exported.txt",
                       },
                      {"angle": 80,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_80-exported.txt",
                       },
                      {"angle": 85,
                       "type_": "dry",
                       "material": "painted_steel",
                       "filepath": "src/dry_painted_steel/dry_kraska_85-exported.txt",
                       },

                      #######################

                      {"angle": 0,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_0-exported.txt",
                       },
                      {"angle": 20,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_20-exported.txt",
                       },
                      {"angle": 30,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_30-exported.txt",
                       },
                      {"angle": 40,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_40-exported.txt",
                       },
                      {"angle": 50,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_50-exported.txt",
                       },
                      {"angle": 55,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_55-exported.txt",
                       },
                      {"angle": 60,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_60-exported.txt",
                       },
                      {"angle": 65,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_65-exported.txt",
                       },
                      {"angle": 70,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_70-exported.txt",
                       },
                      {"angle": 75,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_75-exported.txt",
                       },
                      {"angle": 80,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_80-exported.txt",
                       },
                      {"angle": 85,
                       "type_": "wet",
                       "material": "painted_steel",
                       "filepath": "src/wet_painted_steel/wet_kraska_85-exported.txt",
                       },
                      ]
