DATA_LIST = [{"angle": 0,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон0-exported.txt",
              },
             {"angle": 20,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон20-exported.txt",
              },
             {"angle": 30,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон30-exported.txt",
              },
             {"angle": 40,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон40-exported.txt",
              },
             {"angle": 50,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон50-exported.txt",
              },
             {"angle": 55,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон55-exported.txt",
              },
             {"angle": 60,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон60-exported.txt",
              },
             {"angle": 65,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон65-exported.txt",
              },
             {"angle": 70,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон70-exported.txt",
              },
             {"angle": 75,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон75-exported - Cloud.txt",
              },
             {"angle": 80,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон80-exported - Cloud.txt",
              },
             {"angle": 85,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/wet_concrete/ВлБетон85-exported - Cloud.txt",
              },


             {"angle": 0,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон0-exported.txt",
              },
             {"angle": 20,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон20-exported.txt",
              },
             {"angle": 30,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон30-exported.txt",
              },
             {"angle": 40,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон40-exported.txt",
              },
             {"angle": 50,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон50-exported.txt",
              },
             {"angle": 55,
              "type_": "wet",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон55-exported.txt",
              },
             {"angle": 60,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон60-exported.txt",
              },
             {"angle": 65,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон65-exported.txt",
              },
             {"angle": 70,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон70-exported.txt",
              },
             {"angle": 75,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон75-exported.txt",
              },
             {"angle": 80,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон80-exported.txt",
              },
             {"angle": 85,
              "type_": "dry",
              "material": "concrete",
              "filepath": "src/dry_concrete/Бетон85-exported.txt",
              },
             ]
